---
- name: Monitor Server
  hosts: monitor
  become: true
  
  tasks:
    - name: Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - package

    - name: Install user package
      yum:
        name:
          - mc
          - vim
          - wget
        state: latest
      tags:
        - user-package
        - package

    - name: Install Docker package from EPEL Repo
      yum:
        name:
          - docker
          - docker-compose
        state: latest
      tags:
        - docker-package
        - package
